// <auto-generated />
using System;
using CotizacionesWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CotizacionesWeb.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DbContextCotizaciones))]
    [Migration("20260405235622_AgregarNotificacionCotizacion")]
    partial class AgregarNotificacionCotizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.ArchivoCotizacion", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CotizacionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaArchivado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaReactivacion")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoArchivado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("UsuarioArchiva")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioReactiva")
                        .HasColumnType("int");

                    b.Property<int?>("VersionArchivada")
                        .HasColumnType("int");

                    b.HasKey("ArchivoId");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("FechaArchivado");

                    b.HasIndex("UsuarioArchiva");

                    b.HasIndex("UsuarioReactiva");

                    b.ToTable("ArchivoCotizacion", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Cotizacion", b =>
                {
                    b.Property<string>("CotizacionId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnviadoERP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEnvioERP")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("datetime");

                    b.Property<int?>("InteresadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("CRC");

                    b.Property<decimal>("MontoCotizacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VersionActual")
                        .HasColumnType("int");

                    b.HasKey("CotizacionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InteresadoId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Cotizacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cotizacion_EnviadoERP", "[EnviadoERP] IN ('S', 'N')");
                        });
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.CotizacionVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("CotizacionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailInteresado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmpresaInteresado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaVersion")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NombreInteresado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("NumeroVersion")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TipoCambio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VersionActual")
                        .HasColumnType("int");

                    b.HasKey("VersionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("CotizacionId", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("CotizacionVersion", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.DetalleCotizacionVersion", b =>
                {
                    b.Property<int>("DetalleVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleVersionId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("DetalleVersionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("VersionId");

                    b.ToTable("DetalleCotizacionVersion", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.HistorialCotizacion", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsuarioEvento")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("HistorialId");

                    b.HasIndex("FechaEvento");

                    b.HasIndex("UsuarioEvento");

                    b.HasIndex("VersionId");

                    b.ToTable("HistorialCotizacion", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Interesado", b =>
                {
                    b.Property<int>("InteresadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteresadoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltSync")
                        .HasColumnType("datetime");

                    b.Property<string>("HubspotObjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HubspotObjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TipoInteresado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("InteresadoId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HubspotObjectId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Interesado", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.NotificacionCotizacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<string>("Asunto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CotizacionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDestino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaEnviada")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MensajeError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("VersionId");

                    b.HasIndex("Estado", "FechaProgramada")
                        .HasDatabaseName("IX_NotificacionCotizacion_Estado_FechaProgramada");

                    b.HasIndex("CotizacionId", "VersionId", "TipoNotificacion")
                        .HasDatabaseName("IX_NotificacionCotizacion_CotizacionId_VersionId_TipoNotificacion");

                    b.ToTable("NotificacionCotizacion", (string)null);
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Parametros", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametroId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsModificable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsSensitivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<char>("TipoValor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue('S');

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValorPorDefecto")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ParametroId");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Parametros_Categoria");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Parametros_Codigo");

                    b.HasIndex("EsModificable")
                        .HasDatabaseName("IX_Parametros_EsModificable");

                    b.HasIndex("EsSensitivo")
                        .HasDatabaseName("IX_Parametros_EsSensitivo");

                    b.HasIndex("Categoria", "Codigo")
                        .HasDatabaseName("IX_Parametros_Categoria_Codigo");

                    b.ToTable("Parametros", null, t =>
                        {
                            t.HasCheckConstraint("CK_Parametros_TipoValor", "[TipoValor] IN ('S', 'N', 'B', 'D', 'E')");
                        });
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PermisoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.PermisoRol", b =>
                {
                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("PermisoId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("PermisosRoles");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.ArchivoCotizacion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany("Archivos")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioArchiva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ArchivoCotizacion_Usuarios_UsuarioArchiva");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioReactiva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ArchivoCotizacion_Usuarios_UsuarioReactiva");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Cotizacion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cotizacion_Usuarios_CreatedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Interesado", "Interesado")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("InteresadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Cotizacion_Usuarios_ModifiedBy");

                    b.Navigation("Interesado");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.CotizacionVersion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany("Versiones")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CotizacionVersion_Usuarios_CreatedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CotizacionVersion_Usuarios_ModifiedBy");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.DetalleCotizacionVersion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleCotizacionVersion_Usuarios_CreatedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DetalleCotizacionVersion_Usuarios_ModifiedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.CotizacionVersion", "Version")
                        .WithMany("Detalles")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.HistorialCotizacion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HistorialCotizacion_Usuarios_UsuarioEvento");

                    b.HasOne("CotizacionesWeb.Domain.Entities.CotizacionVersion", "Version")
                        .WithMany("Historiales")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Interesado", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Interesado_Usuarios_CreatedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Interesado_Usuarios_ModifiedBy");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.NotificacionCotizacion", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NotificacionCotizacion_Cotizacion");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NotificacionCotizacion_Usuarios_CreatedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_NotificacionCotizacion_Usuarios_ModifiedBy");

                    b.HasOne("CotizacionesWeb.Domain.Entities.CotizacionVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NotificacionCotizacion_CotizacionVersion");

                    b.Navigation("Cotizacion");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.PermisoRol", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Permiso", "Permiso")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionesWeb.Domain.Entities.Rol", "Rol")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("CotizacionesWeb.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CotizacionesWeb.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Cotizacion", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.CotizacionVersion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Interesado", b =>
                {
                    b.Navigation("Cotizaciones");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Rol", b =>
                {
                    b.Navigation("PermisosRoles");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("CotizacionesWeb.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
